theme = "harbor"
baseurl = "https://blog.dakatsuka.jp"
title = "dakatsuka's blog"
paginate = 3
languageCode = "ja"
DefaultContentLanguage = "ja"
hasCJKLanguage=true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
uglyurls = true

# Optional
# If you use googleAnalytics, you set top-level options in config.toml to the beginning of the config file like other top-level options.
googleAnalytics = "UA-45923728-1"
# and disqus too.
# disqusShortName = "yourdisqusshortname"

#[params.goatcounter]
#  domain="stats.domain.com"

[Author]
  name = "Dai Akatsuka"

[outputs]
  section = ["JSON", "HTML"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about.html"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags.html"
  weight = 3

[[params.nav]]
  identifier = "archives"
  name = "Archives"
  icon = "fas fa-archive fa-lg"
  url = "/archives.html"
  weight = 3

[[params.social]]
  name="twitter"
  url="https://twitter.com/d_akatsuka"
  icon="fab fa-twitter"

[[params.social]]
  name="github"
  url="https://github.com/dakatsuka"
  icon="fab fa-github"

[params]
  uglyURLs = true
  mainSections = ["post"]
  favicon = "favicon.ico"
  customCSS = ["/css/override.css"]
  images = ["/images/logo.png"]

  [params.logo]
    url = "logo.png"
    width = 80
    height = 80
    alt = "logo"